name: app_chat
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  flutter_facebook_auth: ^6.0.2
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^5.0.0
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.2
  pinput: ^3.0.1
  flutter_svg: ^2.0.8
  http: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/