name: "Install Flutter"
description: "Prepare the repo for building"
inputs:
  flutter-version:
    description: "Version of Flutter to use"
    required: false
    default: "3.10.6"
runs:
  using: "composite"
  steps:
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: 'stable'
    - run: flutter --version
      shell: bash

    - name: Install dependencies
      run: dart pub get
      shell: bash